# Generated by Django 3.1.7 on 2021-05-02 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0002_auto_20210501_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonfile',
            name='myfile',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['json'])]),
        ),
    ]
