# Generated by Django 3.1.7 on 2021-05-02 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0004_auto_20210502_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='jsonfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Document_name', max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('myfile', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['json'])])),
            ],
        ),
        migrations.DeleteModel(
            name='jsonfilemedia',
        ),
    ]
