# Generated by Django 3.1.7 on 2021-05-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0005_auto_20210502_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonfile',
            name='createdby',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
